src/Entity/Vehicule.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $titre = null;

    #[Assert\NotBlank(message: 'Ce champs ne peut pas être vide')]
    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[Assert\NotBlank(message: 'Ce champs ne peut pas être vide')]
    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[Assert\NotBlank(message: 'Ce champs ne peut pas être vide')]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car Location{% endblock %}

{% block body %}
<h1 class="text-center my-4">Car Location</h1>

<img src="{{ asset("./carlocation.jpg")}}" alt="">

{% endblock %}

templates/app/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ vehicule.marque }} {{ vehicule.modele }}
{% endblock %}

{% block body %}
<h1 class="text-center my-4">{{ vehicule.marque }} {{ vehicule.modele }}</h1>

<div class="container mt-5">
		<div class="card text-white bg-dark mb-3">
			<div class="card-body">
				<h4 class="card-title">{{ vehicule.marque }} {{ vehicule.modele }}</h4>
				<img src="{{ asset("img/upload/" ~ vehicule.photo) }}" alt="" width="500">
				<p class="card-text"><span class="text-light">Description : </span>{{ vehicule.description }}</p>
				<p class="card-text"><span class="text-light">Prix : </span>{{ vehicule.prixJournalier }} €</p>

			</div>
		</div>
	</div>

<div class="container">
<h2 class="text-center">Reservation</h2>
	{{ form_start(commande) }}
	<div class="row">
	<div class="col-6">{{ form_row(commande.date_heure_depart) }}</div>
	<div class="col-6">{{ form_row(commande.date_heure_fin) }}</div>
	</div>
	<button type="submit" class="btn btn-primary">Envoyer</button>


	{{ form_end(commande) }}
</div>



{% endblock %}

templates/app/vehicules.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des vehicules{% endblock %}

{% block body %}
<h1 class="text-center my-4">Liste des vehicules</h1>

<div class="container">
		<section class="row">
			{# * for valeur in (objet ou tableau) #}
			{% for vehicule in vehicules %}
				<div class="card text-white bg-dark col-md-3 m-3 p-2">
					<div class="card-header">{{ vehicule.marque }} {{ vehicule.modele }}</div>
				<img src="{{ asset("img/upload/" ~ vehicule.photo) }}" alt="" class="p-1">

					<div class="card-body">
					<p><span class="text-light">Prix : </span>{{ vehicule.prixJournalier }} €</p>
                    {# * le filtre |raw permet d'interpreter les balises HTML #}
						<p><span class="text-light">Description : </span>{{ vehicule.description|slice(0, 100) }}</p>
						<div class="text-center">
							<a href="{{ path('show_vehicule', {id: vehicule.id}) }}" class="btn btn-primary">voir plus</a>
						</div>
					</div>
				</div>
			{% endfor %}
		</section>
	</div>


{% endblock %}